declare namespace UnityEditor {
  class CurveEditor {
    // constructors
    constructor(rect: any, curves: UnityEditor.CurveWrapper[], minimalGUI: boolean);
    // methods
    GetTopMostCurveID(curveID: any): boolean;
    OnEnable(): any;
    OnDisable(): any;
    OnDestroy(): any;
    InvalidateBounds(): any;
    FrameClip(horizontally: boolean, vertically: boolean): any;
    FrameSelected(horizontally: boolean, vertically: boolean): any;
    UpdateCurves(curveIds: any, undoText: string): any;
    UpdateCurves(changedCurves: any, undoText: string): any;
    StartLiveEdit(): any;
    EndLiveEdit(): any;
    InLiveEdit(): boolean;
    OnGUI(): any;
    CurveGUI(): any;
    AddKey(cw: UnityEditor.CurveWrapper, key: any): any;
    SelectNone(): any;
    SelectAll(): any;
    IsDraggingKey(): boolean;
    IsDraggingCurveOrRegion(): boolean;
    IsDraggingCurve(cw: UnityEditor.CurveWrapper): boolean;
    IsDraggingRegion(cw1: UnityEditor.CurveWrapper, cw2: UnityEditor.CurveWrapper): boolean;
    BeginTimeRangeSelection(time: number, addToSelection: boolean): any;
    TimeRangeSelectTo(time: number): any;
    EndTimeRangeSelection(): any;
    CancelTimeRangeSelection(): any;
    MovePoints(): any;
    SaveKeySelection(undoLabel: string): any;
    DrawRegion(curve1: UnityEditor.CurveWrapper, curve2: UnityEditor.CurveWrapper, hasFocus: boolean): any;
    GridGUI(): any;
    SetTickMarkerRanges(): any;
    DrawMajorTicks(position: any, frameRate: number): any;
    TimeRuler(position: any, frameRate: number): any;
    TimeRuler(position: any, frameRate: number, labels: boolean, useEntireHeight: boolean, alpha: number): any;
    TimeRuler(position: any, frameRate: number, labels: boolean, useEntireHeight: boolean, alpha: number, timeFormat: UnityEditor.TimeArea.TimeFormat): any;
    BrowseRuler(position: any, time: any, frameRate: number, pickAnywhere: boolean, thumbStyle: any): UnityEditor.TimeArea.TimeRulerDragMode;
    BrowseRuler(position: any, id: number, time: any, frameRate: number, pickAnywhere: boolean, thumbStyle: any): UnityEditor.TimeArea.TimeRulerDragMode;
    FrameToPixel(i: number, frameRate: number, rect: any): number;
    TimeField(rect: any, id: number, time: number, frameRate: number, timeFormat: UnityEditor.TimeArea.TimeFormat): number;
    ValueField(rect: any, id: number, value: number): number;
    FormatTime(time: number, frameRate: number, timeFormat: UnityEditor.TimeArea.TimeFormat): string;
    FormatValue(value: number): string;
    SnapTimeToWholeFPS(time: number, frameRate: number): number;
    SetShownHRangeInsideMargins(min: number, max: number): any;
    SetShownHRange(min: number, max: number): any;
    SetShownVRangeInsideMargins(min: number, max: number): any;
    SetShownVRange(min: number, max: number): any;
    DrawingToViewTransformPoint(lhs: any): any;
    DrawingToViewTransformPoint(lhs: any): any;
    ViewToDrawingTransformPoint(lhs: any): any;
    ViewToDrawingTransformPoint(lhs: any): any;
    DrawingToViewTransformVector(lhs: any): any;
    DrawingToViewTransformVector(lhs: any): any;
    ViewToDrawingTransformVector(lhs: any): any;
    ViewToDrawingTransformVector(lhs: any): any;
    NormalizeInViewSpace(vec: any): any;
    BeginViewGUI(): any;
    HandleZoomAndPanEvents(area: any): any;
    EndViewGUI(): any;
    SetScaleFocused(focalPoint: any, newScale: any): any;
    SetScaleFocused(focalPoint: any, newScale: any, lockHorizontal: boolean, lockVertical: boolean): any;
    SetTransform(newTranslation: any, newScale: any): any;
    EnforceScaleAndRange(): any;
    PixelToTime(pixelX: number, rect: any): number;
    TimeToPixel(time: number, rect: any): number;
    PixelDeltaToTime(rect: any): number;
    Equals(obj: any): boolean;
    GetHashCode(): number;
    GetType(): any;
    ToString(): string;
    // properties
    animationCurves: UnityEditor.CurveWrapper[];
    readonly syncTimeDuringDrag: boolean;
    readonly timeFormat: UnityEditor.TimeArea.TimeFormat;
    settings: UnityEditor.CurveEditorSettings;
    tangentColor: any;
    readonly hasSelection: boolean;
    readonly selectionBounds: any;
    readonly curveBounds: any;
    readonly drawingBounds: any;
    hTicks: UnityEditor.TickHandler;
    vTicks: UnityEditor.TickHandler;
    hRangeLocked: boolean;
    vRangeLocked: boolean;
    hBaseRangeMin: number;
    hBaseRangeMax: number;
    vBaseRangeMin: number;
    vBaseRangeMax: number;
    hAllowExceedBaseRangeMin: boolean;
    hAllowExceedBaseRangeMax: boolean;
    vAllowExceedBaseRangeMin: boolean;
    vAllowExceedBaseRangeMax: boolean;
    hRangeMin: number;
    hRangeMax: number;
    vRangeMin: number;
    vRangeMax: number;
    hScaleMin: number;
    hScaleMax: number;
    vScaleMin: number;
    vScaleMax: number;
    scaleWithWindow: boolean;
    hSlider: boolean;
    vSlider: boolean;
    ignoreScrollWheelUntilClicked: boolean;
    enableMouseInput: boolean;
    uniformScale: boolean;
    upDirection: UnityEditor.ZoomableArea.YDirection;
    readonly scale: any;
    readonly translation: any;
    leftmargin: number;
    rightmargin: number;
    topmargin: number;
    bottommargin: number;
    rect: any;
    readonly drawRect: any;
    shownArea: any;
    shownAreaInsideMargins: any;
    readonly drawingToViewMatrix: any;
    readonly mousePositionInDrawing: any;
    // fields
    curvesUpdated: UnityEditor.CurveEditor.CallbackFunction;
    state: UnityEditor.ICurveEditorState;
    invSnap: number;
    m_UniformScale: boolean;
  }
}
