declare namespace UnityEditor {
  class Handles {
    // constructors
    constructor();
    // methods
    static PositionHandle(position: any, rotation: any): any;
    static RotationHandle(rotation: any, position: any): any;
    static ScaleHandle(scale: any, position: any, rotation: any, size: number): any;
    static RadiusHandle(rotation: any, position: any, radius: number, handlesOnly: boolean): number;
    static RadiusHandle(rotation: any, position: any, radius: number): number;
    static Slider(position: any, direction: any): any;
    static Slider(position: any, direction: any, size: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: number): any;
    static Slider2D(id: number, handlePos: any, offset: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any): any;
    static Slider2D(id: number, handlePos: any, offset: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(id: number, handlePos: any, offset: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any): any;
    static Slider2D(id: number, handlePos: any, offset: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(id: number, handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any): any;
    static Slider2D(id: number, handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(id: number, handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any): any;
    static Slider2D(id: number, handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: any, drawHelper: boolean): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: number): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, drawFunc: UnityEditor.Handles.DrawCapFunction, snap: number, drawHelper: boolean): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: number): any;
    static Slider2D(handlePos: any, handleDir: any, slideDir1: any, slideDir2: any, handleSize: number, capFunction: UnityEditor.Handles.CapFunction, snap: number, drawHelper: boolean): any;
    static FreeRotateHandle(rotation: any, position: any, size: number): any;
    static FreeMoveHandle(position: any, rotation: any, size: number, snap: any, capFunc: UnityEditor.Handles.DrawCapFunction): any;
    static ScaleSlider(scale: number, position: any, direction: any, rotation: any, size: number, snap: number): number;
    static ScaleValueHandle(value: number, position: any, rotation: any, size: number, capFunc: UnityEditor.Handles.DrawCapFunction, snap: number): number;
    static Disc(rotation: any, position: any, axis: any, size: number, cutoffPlane: boolean, snap: number): any;
    static Button(position: any, direction: any, size: number, pickSize: number, capFunc: UnityEditor.Handles.DrawCapFunction): boolean;
    static SnapValue(val: number, snap: number): number;
    static CubeCap(controlID: number, position: any, rotation: any, size: number): void;
    static SphereCap(controlID: number, position: any, rotation: any, size: number): void;
    static ConeCap(controlID: number, position: any, rotation: any, size: number): void;
    static CylinderCap(controlID: number, position: any, rotation: any, size: number): void;
    static RectangleCap(controlID: number, position: any, rotation: any, size: number): void;
    static SelectionFrame(controlID: number, position: any, rotation: any, size: number): void;
    static DotCap(controlID: number, position: any, rotation: any, size: number): void;
    static CircleCap(controlID: number, position: any, rotation: any, size: number): void;
    static ArrowCap(controlID: number, position: any, rotation: any, size: number): void;
    static DrawCylinder(controlID: number, position: any, rotation: any, size: number): void;
    static DrawSphere(controlID: number, position: any, rotation: any, size: number): void;
    static DrawRectangle(controlID: number, position: any, rotation: any, size: number): void;
    static DrawCube(controlID: number, position: any, rotation: any, size: number): void;
    static DrawArrow(controlID: number, position: any, rotation: any, size: number): void;
    static DrawCone(controlID: number, position: any, rotation: any, size: number): void;
    static DrawAAPolyLine(points: any[]): void;
    static DrawAAPolyLine(width: number, points: any[]): void;
    static DrawAAPolyLine(lineTex: any, points: any[]): void;
    static DrawAAPolyLine(width: number, actualNumberOfPoints: number, points: any[]): void;
    static DrawAAPolyLine(lineTex: any, width: number, points: any[]): void;
    static DrawAAConvexPolygon(points: any[]): void;
    static DrawBezier(startPosition: any, endPosition: any, startTangent: any, endTangent: any, color: any, texture: any, width: number): void;
    static DrawWireDisc(center: any, normal: any, radius: number): void;
    static DrawWireArc(center: any, normal: any, from: any, angle: number, radius: number): void;
    static DrawSolidRectangleWithOutline(rectangle: any, faceColor: any, outlineColor: any): void;
    static DrawSolidRectangleWithOutline(verts: any[], faceColor: any, outlineColor: any): void;
    static DrawSolidDisc(center: any, normal: any, radius: number): void;
    static DrawSolidArc(center: any, normal: any, from: any, angle: number, radius: number): void;
    static Label(position: any, text: string): void;
    static Label(position: any, image: any): void;
    static Label(position: any, content: any): void;
    static Label(position: any, text: string, style: any): void;
    static Label(position: any, content: any, style: any): void;
    static GetMainGameViewSize(): any;
    static ClearCamera(position: any, camera: any): void;
    static DrawCamera(position: any, camera: any): void;
    static DrawCamera(position: any, camera: any, drawMode: UnityEditor.DrawCameraMode): void;
    static SetCamera(camera: any): void;
    static SetCamera(position: any, camera: any): void;
    static BeginGUI(): void;
    static BeginGUI(position: any): void;
    static EndGUI(): void;
    static MakeBezierPoints(startPosition: any, endPosition: any, startTangent: any, endTangent: any, division: number): any[];
    static DrawPolyLine(points: any[]): void;
    static DrawLine(p1: any, p2: any): void;
    static DrawLines(lineSegments: any[]): void;
    static DrawLines(points: any[], segmentIndices: number[]): void;
    static DrawDottedLine(p1: any, p2: any, screenSpaceSize: number): void;
    static DrawDottedLines(lineSegments: any[], screenSpaceSize: number): void;
    static DrawDottedLines(points: any[], segmentIndices: number[], screenSpaceSize: number): void;
    static DrawWireCube(center: any, size: any): void;
    static Slider(position: any, direction: any, size: number, capFunction: UnityEditor.Handles.CapFunction, snap: number): any;
    static FreeMoveHandle(position: any, rotation: any, size: number, snap: any, capFunction: UnityEditor.Handles.CapFunction): any;
    static ScaleValueHandle(value: number, position: any, rotation: any, size: number, capFunction: UnityEditor.Handles.CapFunction, snap: number): number;
    static Button(position: any, direction: any, size: number, pickSize: number, capFunction: UnityEditor.Handles.CapFunction): boolean;
    static CubeHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static SphereHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static ConeHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static CylinderHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static RectangleHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static DotHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static CircleHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static ArrowHandleCap(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static DrawSelectionFrame(controlID: number, position: any, rotation: any, size: number, eventType: any): void;
    static DoPositionHandle(position: any, rotation: any): any;
    static DoRotationHandle(rotation: any, position: any): any;
    static DoScaleHandle(scale: any, position: any, rotation: any, size: number): any;
    Equals(obj: any): boolean;
    GetHashCode(): number;
    GetType(): any;
    ToString(): string;
    // properties
    static readonly xAxisColor: any;
    static readonly yAxisColor: any;
    static readonly zAxisColor: any;
    static readonly centerColor: any;
    static readonly selectedColor: any;
    static readonly secondaryColor: any;
    static lighting: boolean;
    static color: any;
    static matrix: any;
    static readonly inverseMatrix: any;
    currentCamera: any;
    // fields
  }
}
