declare namespace UnityEditor.TextureImporterInspector {
  class Styles extends System.Object {
    // constructors
    constructor();
    // methods
    // properties
    // fields
    textureTypeTitle: any;
    textureTypeOptions: any[];
    textureTypeValues: number[];
    textureShape: any;
    textureShapeOptionsDictionnary: any;
    textureShapeValuesDictionnary: any;
    filterMode: any;
    filterModeOptions: any[];
    cookieType: any;
    cookieOptions: any[];
    generateFromBump: any;
    bumpiness: any;
    bumpFiltering: any;
    bumpFilteringOptions: any[];
    cubemap: any;
    cubemapOptions: any[];
    cubemapValues2: number[];
    cubemapConvolution: any;
    cubemapConvolutionOptions: any[];
    cubemapConvolutionValues: number[];
    seamlessCubemap: any;
    textureFormat: any;
    defaultPlatform: any;
    mipmapFadeOutToggle: any;
    mipmapFadeOut: any;
    readWrite: any;
    alphaSource: any;
    alphaSourceOptions: any[];
    alphaSourceValues: number[];
    generateMipMaps: any;
    sRGBTexture: any;
    borderMipMaps: any;
    mipMapFilter: any;
    mipMapFilterOptions: any[];
    npot: any;
    generateCubemap: any;
    compressionQuality: any;
    compressionQualitySlider: any;
    mobileCompressionQualityOptions: any[];
    spriteMode: any;
    spriteModeOptions: any[];
    spriteMeshTypeOptions: any[];
    spritePackingTag: any;
    spritePixelsPerUnit: any;
    spriteExtrude: any;
    spriteMeshType: any;
    spriteAlignment: any;
    spriteAlignmentOptions: any[];
    alphaIsTransparency: any;
    etc1Compression: any;
    crunchedCompression: any;
    showAdvanced: any;
  }
}
