declare namespace UnityEditor {
  class EditorGUI {
    // constructors
    constructor();
    // methods
    static LabelField(position: any, label: string): any;
    static LabelField(position: any, label: string, style: any): any;
    static LabelField(position: any, label: any): any;
    static LabelField(position: any, label: any, style: any): any;
    static LabelField(position: any, label: string, label2: string): any;
    static LabelField(position: any, label: string, label2: string, style: any): any;
    static LabelField(position: any, label: any, label2: any): any;
    static LabelField(position: any, label: any, label2: any, style: any): any;
    static ToggleLeft(position: any, label: string, value: boolean): boolean;
    static ToggleLeft(position: any, label: string, value: boolean, labelStyle: any): boolean;
    static ToggleLeft(position: any, label: any, value: boolean): boolean;
    static ToggleLeft(position: any, label: any, value: boolean, labelStyle: any): boolean;
    static TextField(position: any, text: string): string;
    static TextField(position: any, text: string, style: any): string;
    static TextField(position: any, label: string, text: string): string;
    static TextField(position: any, label: string, text: string, style: any): string;
    static TextField(position: any, label: any, text: string): string;
    static TextField(position: any, label: any, text: string, style: any): string;
    static DelayedTextField(position: any, text: string): string;
    static DelayedTextField(position: any, text: string, style: any): string;
    static DelayedTextField(position: any, label: string, text: string): string;
    static DelayedTextField(position: any, label: string, text: string, style: any): string;
    static DelayedTextField(position: any, label: any, text: string): string;
    static DelayedTextField(position: any, label: any, text: string, style: any): string;
    static DelayedTextField(position: any, property: UnityEditor.SerializedProperty): any;
    static DelayedTextField(position: any, property: UnityEditor.SerializedProperty, label: any): any;
    static DelayedTextField(position: any, controlId: number, label: any, text: string): string;
    static DelayedTextField(position: any, controlId: number, label: any, text: string, style: any): string;
    static TextArea(position: any, text: string): string;
    static TextArea(position: any, text: string, style: any): string;
    static SelectableLabel(position: any, text: string): any;
    static SelectableLabel(position: any, text: string, style: any): any;
    static PasswordField(position: any, password: string): string;
    static PasswordField(position: any, password: string, style: any): string;
    static PasswordField(position: any, label: string, password: string): string;
    static PasswordField(position: any, label: string, password: string, style: any): string;
    static PasswordField(position: any, label: any, password: string): string;
    static PasswordField(position: any, label: any, password: string, style: any): string;
    static FloatField(position: any, value: number): number;
    static FloatField(position: any, value: number, style: any): number;
    static FloatField(position: any, label: string, value: number): number;
    static FloatField(position: any, label: string, value: number, style: any): number;
    static FloatField(position: any, label: any, value: number): number;
    static FloatField(position: any, label: any, value: number, style: any): number;
    static DelayedFloatField(position: any, value: number): number;
    static DelayedFloatField(position: any, value: number, style: any): number;
    static DelayedFloatField(position: any, label: string, value: number): number;
    static DelayedFloatField(position: any, label: string, value: number, style: any): number;
    static DelayedFloatField(position: any, label: any, value: number): number;
    static DelayedFloatField(position: any, label: any, value: number, style: any): number;
    static DelayedFloatField(position: any, property: UnityEditor.SerializedProperty): any;
    static DelayedFloatField(position: any, property: UnityEditor.SerializedProperty, label: any): any;
    static DoubleField(position: any, value: number): number;
    static DoubleField(position: any, value: number, style: any): number;
    static DoubleField(position: any, label: string, value: number): number;
    static DoubleField(position: any, label: string, value: number, style: any): number;
    static DoubleField(position: any, label: any, value: number): number;
    static DoubleField(position: any, label: any, value: number, style: any): number;
    static DelayedDoubleField(position: any, value: number): number;
    static DelayedDoubleField(position: any, value: number, style: any): number;
    static DelayedDoubleField(position: any, label: string, value: number): number;
    static DelayedDoubleField(position: any, label: string, value: number, style: any): number;
    static DelayedDoubleField(position: any, label: any, value: number): number;
    static DelayedDoubleField(position: any, label: any, value: number, style: any): number;
    static IntField(position: any, value: number): number;
    static IntField(position: any, value: number, style: any): number;
    static IntField(position: any, label: string, value: number): number;
    static IntField(position: any, label: string, value: number, style: any): number;
    static IntField(position: any, label: any, value: number): number;
    static IntField(position: any, label: any, value: number, style: any): number;
    static DelayedIntField(position: any, value: number): number;
    static DelayedIntField(position: any, value: number, style: any): number;
    static DelayedIntField(position: any, label: string, value: number): number;
    static DelayedIntField(position: any, label: string, value: number, style: any): number;
    static DelayedIntField(position: any, label: any, value: number): number;
    static DelayedIntField(position: any, label: any, value: number, style: any): number;
    static DelayedIntField(position: any, property: UnityEditor.SerializedProperty): any;
    static DelayedIntField(position: any, property: UnityEditor.SerializedProperty, label: any): any;
    static LongField(position: any, value: number): number;
    static LongField(position: any, value: number, style: any): number;
    static LongField(position: any, label: string, value: number): number;
    static LongField(position: any, label: string, value: number, style: any): number;
    static LongField(position: any, label: any, value: number): number;
    static LongField(position: any, label: any, value: number, style: any): number;
    static Popup(position: any, selectedIndex: number, displayedOptions: string[]): number;
    static Popup(position: any, selectedIndex: number, displayedOptions: string[], style: any): number;
    static Popup(position: any, selectedIndex: number, displayedOptions: any[]): number;
    static Popup(position: any, selectedIndex: number, displayedOptions: any[], style: any): number;
    static Popup(position: any, label: string, selectedIndex: number, displayedOptions: string[]): number;
    static Popup(position: any, label: string, selectedIndex: number, displayedOptions: string[], style: any): number;
    static Popup(position: any, label: any, selectedIndex: number, displayedOptions: any[]): number;
    static Popup(position: any, label: any, selectedIndex: number, displayedOptions: any[], style: any): number;
    static EnumPopup(position: any, selected: any): any;
    static EnumPopup(position: any, selected: any, style: any): any;
    static EnumPopup(position: any, label: string, selected: any): any;
    static EnumPopup(position: any, label: string, selected: any, style: any): any;
    static EnumPopup(position: any, label: any, selected: any): any;
    static EnumPopup(position: any, label: any, selected: any, style: any): any;
    static EnumMaskPopup(position: any, label: string, selected: any): any;
    static EnumMaskPopup(position: any, label: string, selected: any, style: any): any;
    static EnumMaskPopup(position: any, label: any, selected: any): any;
    static EnumMaskPopup(position: any, label: any, selected: any, style: any): any;
    static IntPopup(position: any, selectedValue: number, displayedOptions: string[], optionValues: number[]): number;
    static IntPopup(position: any, selectedValue: number, displayedOptions: string[], optionValues: number[], style: any): number;
    static IntPopup(position: any, selectedValue: number, displayedOptions: any[], optionValues: number[]): number;
    static IntPopup(position: any, selectedValue: number, displayedOptions: any[], optionValues: number[], style: any): number;
    static IntPopup(position: any, label: any, selectedValue: number, displayedOptions: any[], optionValues: number[]): number;
    static IntPopup(position: any, label: any, selectedValue: number, displayedOptions: any[], optionValues: number[], style: any): number;
    static IntPopup(position: any, property: UnityEditor.SerializedProperty, displayedOptions: any[], optionValues: number[]): any;
    static IntPopup(position: any, property: UnityEditor.SerializedProperty, displayedOptions: any[], optionValues: number[], label: any): any;
    static IntPopup(position: any, label: string, selectedValue: number, displayedOptions: string[], optionValues: number[]): number;
    static IntPopup(position: any, label: string, selectedValue: number, displayedOptions: string[], optionValues: number[], style: any): number;
    static TagField(position: any, tag: string): string;
    static TagField(position: any, tag: string, style: any): string;
    static TagField(position: any, label: string, tag: string): string;
    static TagField(position: any, label: string, tag: string, style: any): string;
    static TagField(position: any, label: any, tag: string): string;
    static TagField(position: any, label: any, tag: string, style: any): string;
    static LayerField(position: any, layer: number): number;
    static LayerField(position: any, layer: number, style: any): number;
    static LayerField(position: any, label: string, layer: number): number;
    static LayerField(position: any, label: string, layer: number, style: any): number;
    static LayerField(position: any, label: any, layer: number): number;
    static LayerField(position: any, label: any, layer: number, style: any): number;
    static MaskField(position: any, label: any, mask: number, displayedOptions: string[]): number;
    static MaskField(position: any, label: any, mask: number, displayedOptions: string[], style: any): number;
    static MaskField(position: any, label: string, mask: number, displayedOptions: string[]): number;
    static MaskField(position: any, label: string, mask: number, displayedOptions: string[], style: any): number;
    static MaskField(position: any, mask: number, displayedOptions: string[]): number;
    static MaskField(position: any, mask: number, displayedOptions: string[], style: any): number;
    static EnumMaskField(position: any, label: any, enumValue: any): any;
    static EnumMaskField(position: any, label: any, enumValue: any, style: any): any;
    static EnumMaskField(position: any, label: string, enumValue: any): any;
    static EnumMaskField(position: any, label: string, enumValue: any, style: any): any;
    static EnumMaskField(position: any, enumValue: any): any;
    static EnumMaskField(position: any, enumValue: any, style: any): any;
    static Foldout(position: any, foldout: boolean, content: string): boolean;
    static Foldout(position: any, foldout: boolean, content: string, style: any): boolean;
    static Foldout(position: any, foldout: boolean, content: string, toggleOnLabelClick: boolean): boolean;
    static Foldout(position: any, foldout: boolean, content: string, toggleOnLabelClick: boolean, style: any): boolean;
    static Foldout(position: any, foldout: boolean, content: any): boolean;
    static Foldout(position: any, foldout: boolean, content: any, style: any): boolean;
    static Foldout(position: any, foldout: boolean, content: any, toggleOnLabelClick: boolean): boolean;
    static Foldout(position: any, foldout: boolean, content: any, toggleOnLabelClick: boolean, style: any): boolean;
    static HandlePrefixLabel(totalPosition: any, labelPosition: any, label: any, id: number): any;
    static HandlePrefixLabel(totalPosition: any, labelPosition: any, label: any): any;
    static HandlePrefixLabel(totalPosition: any, labelPosition: any, label: any, id: number, style: any): any;
    static DrawTextureAlpha(position: any, image: any, scaleMode: any): any;
    static DrawTextureAlpha(position: any, image: any): any;
    static DrawTextureAlpha(position: any, image: any, scaleMode: any, imageAspect: number): any;
    static DrawTextureTransparent(position: any, image: any, scaleMode: any): any;
    static DrawTextureTransparent(position: any, image: any): any;
    static DrawTextureTransparent(position: any, image: any, scaleMode: any, imageAspect: number): any;
    static DrawPreviewTexture(position: any, image: any, mat: any, scaleMode: any): any;
    static DrawPreviewTexture(position: any, image: any, mat: any): any;
    static DrawPreviewTexture(position: any, image: any): any;
    static DrawPreviewTexture(position: any, image: any, mat: any, scaleMode: any, imageAspect: number): any;
    static GetPropertyHeight(property: UnityEditor.SerializedProperty, label: any): number;
    static GetPropertyHeight(property: UnityEditor.SerializedProperty): number;
    static GetPropertyHeight(property: UnityEditor.SerializedProperty, label: any, includeChildren: boolean): number;
    static PropertyField(position: any, property: UnityEditor.SerializedProperty): boolean;
    static PropertyField(position: any, property: UnityEditor.SerializedProperty, includeChildren: boolean): boolean;
    static PropertyField(position: any, property: UnityEditor.SerializedProperty, label: any): boolean;
    static PropertyField(position: any, property: UnityEditor.SerializedProperty, label: any, includeChildren: boolean): boolean;
    static FocusTextInControl(name: string): any;
    static BeginDisabledGroup(disabled: boolean): any;
    static EndDisabledGroup(): any;
    static BeginChangeCheck(): any;
    static EndChangeCheck(): boolean;
    static DropShadowLabel(position: any, text: string): any;
    static DropShadowLabel(position: any, content: any): any;
    static DropShadowLabel(position: any, text: string, style: any): any;
    static DropShadowLabel(position: any, content: any, style: any): any;
    static Toggle(position: any, value: boolean): boolean;
    static Toggle(position: any, label: string, value: boolean): boolean;
    static Toggle(position: any, value: boolean, style: any): boolean;
    static Toggle(position: any, label: string, value: boolean, style: any): boolean;
    static Toggle(position: any, label: any, value: boolean): boolean;
    static Toggle(position: any, label: any, value: boolean, style: any): boolean;
    static DoPasswordField(id: number, position: any, password: string, style: any): string;
    static DoPasswordField(id: number, position: any, label: any, password: string, style: any): string;
    static Slider(position: any, value: number, leftValue: number, rightValue: number): number;
    static Slider(position: any, label: string, value: number, leftValue: number, rightValue: number): number;
    static Slider(position: any, label: any, value: number, leftValue: number, rightValue: number): number;
    static Slider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number): any;
    static Slider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number, label: string): any;
    static Slider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number, label: any): any;
    static IntSlider(position: any, value: number, leftValue: number, rightValue: number): number;
    static IntSlider(position: any, label: string, value: number, leftValue: number, rightValue: number): number;
    static IntSlider(position: any, label: any, value: number, leftValue: number, rightValue: number): number;
    static IntSlider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number): any;
    static IntSlider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number, label: string): any;
    static IntSlider(position: any, property: UnityEditor.SerializedProperty, leftValue: number, rightValue: number, label: any): any;
    static MinMaxSlider(label: any, position: any, minValue: any, maxValue: any, minLimit: number, maxLimit: number): any;
    static MinMaxSlider(position: any, label: string, minValue: any, maxValue: any, minLimit: number, maxLimit: number): any;
    static MinMaxSlider(position: any, label: any, minValue: any, maxValue: any, minLimit: number, maxLimit: number): any;
    static MinMaxSlider(position: any, minValue: any, maxValue: any, minLimit: number, maxLimit: number): any;
    static ObjectField(position: any, property: UnityEditor.SerializedProperty): any;
    static ObjectField(position: any, property: UnityEditor.SerializedProperty, label: any): any;
    static ObjectField(position: any, property: UnityEditor.SerializedProperty, objType: any): any;
    static ObjectField(position: any, property: UnityEditor.SerializedProperty, objType: any, label: any): any;
    static ObjectField(position: any, obj: any, objType: any, allowSceneObjects: boolean): any;
    static ObjectField(position: any, obj: any, objType: any): any;
    static ObjectField(position: any, label: string, obj: any, objType: any, allowSceneObjects: boolean): any;
    static ObjectField(position: any, label: string, obj: any, objType: any): any;
    static ObjectField(position: any, label: any, obj: any, objType: any, allowSceneObjects: boolean): any;
    static ObjectField(position: any, label: any, obj: any, objType: any): any;
    static IndentedRect(source: any): any;
    static Vector2Field(position: any, label: string, value: any): any;
    static Vector2Field(position: any, label: any, value: any): any;
    static Vector3Field(position: any, label: string, value: any): any;
    static Vector3Field(position: any, label: any, value: any): any;
    static Vector4Field(position: any, label: string, value: any): any;
    static Vector4Field(position: any, label: any, value: any): any;
    static RectField(position: any, value: any): any;
    static RectField(position: any, label: string, value: any): any;
    static RectField(position: any, label: any, value: any): any;
    static BoundsField(position: any, value: any): any;
    static BoundsField(position: any, label: string, value: any): any;
    static BoundsField(position: any, label: any, value: any): any;
    static MultiFloatField(position: any, label: any, subLabels: any[], values: number[]): any;
    static MultiFloatField(position: any, subLabels: any[], values: number[]): any;
    static MultiPropertyField(position: any, subLabels: any[], valuesIterator: UnityEditor.SerializedProperty, label: any): any;
    static MultiPropertyField(position: any, subLabels: any[], valuesIterator: UnityEditor.SerializedProperty): any;
    static ColorField(position: any, value: any): any;
    static ColorField(position: any, label: string, value: any): any;
    static ColorField(position: any, label: any, value: any): any;
    static ColorField(position: any, label: any, value: any, showEyedropper: boolean, showAlpha: boolean, hdr: boolean, hdrConfig: UnityEditor.ColorPickerHDRConfig): any;
    static CurveField(position: any, value: any): any;
    static CurveField(position: any, label: string, value: any): any;
    static CurveField(position: any, label: any, value: any): any;
    static CurveField(position: any, value: any, color: any, ranges: any): any;
    static CurveField(position: any, label: string, value: any, color: any, ranges: any): any;
    static CurveField(position: any, label: any, value: any, color: any, ranges: any): any;
    static CurveField(position: any, property: UnityEditor.SerializedProperty, color: any, ranges: any): any;
    static CurveField(position: any, property: UnityEditor.SerializedProperty, color: any, ranges: any, label: any): any;
    static InspectorTitlebar(position: any, targetObjs: any[]): any;
    static InspectorTitlebar(position: any, foldout: boolean, targetObj: any, expandable: boolean): boolean;
    static InspectorTitlebar(position: any, foldout: boolean, targetObjs: any[], expandable: boolean): boolean;
    static ProgressBar(position: any, value: number, text: string): any;
    static HelpBox(position: any, message: string, type: UnityEditor.MessageType): any;
    static PrefixLabel(totalPosition: any, label: any): any;
    static PrefixLabel(totalPosition: any, label: any, style: any): any;
    static PrefixLabel(totalPosition: any, id: number, label: any): any;
    static PrefixLabel(totalPosition: any, id: number, label: any, style: any): any;
    static BeginProperty(totalPosition: any, label: any, property: UnityEditor.SerializedProperty): any;
    static EndProperty(): any;
    static GetPropertyHeight(type: UnityEditor.SerializedPropertyType, label: any): number;
    static DrawRect(rect: any, color: any): any;
    Equals(obj: any): boolean;
    GetHashCode(): number;
    GetType(): any;
    ToString(): string;
    // properties
    static showMixedValue: boolean;
    static readonly actionKey: boolean;
    static indentLevel: number;
    // fields
  }
}
