declare namespace UnityEditorInternal {
  class AnimationWindowState {
    // constructors
    constructor();
    // methods
    OnGUI(): any;
    ForceRefresh(): any;
    OnEnable(): any;
    OnDisable(): any;
    OnDestroy(): any;
    OnSelectionChanged(): any;
    UndoRedoPerformed(): any;
    SaveKeySelection(undoLabel: string): any;
    SaveCurve(curve: UnityEditorInternal.AnimationWindowCurve): any;
    SaveCurve(curve: UnityEditorInternal.AnimationWindowCurve, undoLabel: string): any;
    RemoveCurve(curve: UnityEditorInternal.AnimationWindowCurve, undoLabel: string): any;
    AnyKeyIsSelected(dopeline: UnityEditorInternal.DopeLine): boolean;
    KeyIsSelected(keyframe: UnityEditorInternal.AnimationWindowKeyframe): boolean;
    SelectKey(keyframe: UnityEditorInternal.AnimationWindowKeyframe): any;
    SelectKeysFromDopeline(dopeline: UnityEditorInternal.DopeLine): any;
    UnselectKey(keyframe: UnityEditorInternal.AnimationWindowKeyframe): any;
    UnselectKeysFromDopeline(dopeline: UnityEditorInternal.DopeLine): any;
    DeleteSelectedKeys(): any;
    DeleteKeys(keys: any): any;
    StartLiveEdit(): any;
    EndLiveEdit(): any;
    InLiveEdit(): boolean;
    MoveSelectedKeys(deltaTime: number, snapToFrame: boolean): any;
    TransformSelectedKeys(matrix: any, flipX: boolean, flipY: boolean, snapToFrame: boolean): any;
    TransformRippleKeys(matrix: any, t1: number, t2: number, flipX: boolean, snapToFrame: boolean): any;
    CopyKeys(): any;
    CopyAllActiveCurves(): any;
    PasteKeys(): any;
    ClearSelections(): any;
    ClearKeySelections(): any;
    ClearHierarchySelection(): any;
    ResampleAnimation(): any;
    Repaint(): any;
    GetAggregateKeys(hierarchyNode: UnityEditorInternal.AnimationWindowHierarchyNode): any;
    OnHierarchySelectionChanged(selectedInstanceIDs: number[]): any;
    HandleHierarchySelectionChanged(selectedInstanceIDs: number[], triggerSceneSelectionSync: boolean): any;
    SelectHierarchyItem(dopeline: UnityEditorInternal.DopeLine, additive: boolean): any;
    SelectHierarchyItem(dopeline: UnityEditorInternal.DopeLine, additive: boolean, triggerSceneSelectionSync: boolean): any;
    SelectHierarchyItem(hierarchyNodeID: number, additive: boolean, triggerSceneSelectionSync: boolean): any;
    UnSelectHierarchyItem(dopeline: UnityEditorInternal.DopeLine): any;
    UnSelectHierarchyItem(hierarchyNodeID: number): any;
    GetAffectedHierarchyIDs(keyframes: any): any;
    GetAffectedDopelines(keyframes: any): any;
    GetAffectedCurves(keyframes: any): any;
    GetDopeline(selectedInstanceID: number): UnityEditorInternal.DopeLine;
    PixelToTime(pixel: number): number;
    PixelToTime(pixel: number, snap: UnityEditorInternal.AnimationWindowState.SnapMode): number;
    TimeToPixel(time: number): number;
    TimeToPixel(time: number, snap: UnityEditorInternal.AnimationWindowState.SnapMode): number;
    SnapToFrame(time: number, snap: UnityEditorInternal.AnimationWindowState.SnapMode): number;
    SnapToFrame(time: number, fps: number): number;
    FormatFrame(frame: number, frameDigits: number): string;
    TimeToFrame(time: number): number;
    FrameToTime(frame: number): number;
    TimeToFrameFloor(time: number): number;
    TimeToFrameRound(time: number): number;
    FrameToPixel(i: number, rect: any): number;
    FrameDeltaToPixel(rect: any): number;
    TimeToPixel(time: number, rect: any): number;
    PixelToTime(pixelX: number, rect: any): number;
    PixelDeltaToTime(rect: any): number;
    SetDirty(): any;
    ToString(): string;
    GetInstanceID(): number;
    GetHashCode(): number;
    Equals(other: any): boolean;
    GetType(): any;
    // properties
    readonly selection: UnityEditorInternal.AnimationWindowSelection;
    selectedItem: UnityEditorInternal.AnimationWindowSelectionItem;
    readonly activeAnimationClip: any;
    readonly activeGameObject: any;
    readonly activeRootGameObject: any;
    readonly activeAnimationPlayer: any;
    readonly animatorIsOptimized: boolean;
    locked: boolean;
    readonly disabled: boolean;
    refresh: UnityEditorInternal.AnimationWindowState.RefreshType;
    readonly allCurves: any;
    readonly activeCurves: any;
    readonly activeCurveWrappers: any;
    readonly dopelines: any;
    readonly selectedHierarchyNodes: any;
    activeKeyframe: UnityEditorInternal.AnimationWindowKeyframe;
    readonly selectedKeys: any;
    readonly syncTimeDuringDrag: boolean;
    clipFrameRate: number;
    frameRate: number;
    frame: number;
    currentTime: number;
    readonly time: UnityEditorInternal.AnimationKeyTime;
    timeFormat: UnityEditor.TimeArea.TimeFormat;
    playing: boolean;
    readonly canRecord: boolean;
    recording: boolean;
    policy: UnityEditorInternal.AnimationWindowPolicy;
    timeArea: UnityEditor.TimeArea;
    readonly pixelPerSecond: number;
    readonly zeroTimePixel: number;
    readonly minVisibleTime: number;
    readonly maxVisibleTime: number;
    readonly visibleTimeSpan: number;
    readonly minVisibleFrame: number;
    readonly maxVisibleFrame: number;
    readonly visibleFrameSpan: number;
    readonly minTime: number;
    readonly maxTime: number;
    readonly timeRange: any;
    name: string;
    hideFlags: any;
    // fields
    hierarchyState: UnityEditorInternal.AnimationWindowHierarchyState;
    animEditor: UnityEditor.AnimEditor;
    showCurveEditor: boolean;
    onStartLiveEdit: any;
    onEndLiveEdit: any;
    hierarchyData: UnityEditorInternal.AnimationWindowHierarchyDataSource;
    static kDefaultFrameRate: number;
    static kEditCurveUndoLabel: string;
    onFrameRateChange: any;
  }
}
