declare namespace UnityEngine {
  class AndroidJNI {
    // constructors
    private constructor();
    // methods
    static AttachCurrentThread(): number;
    static DetachCurrentThread(): number;
    static GetVersion(): number;
    static FindClass(name: string): any;
    static FromReflectedMethod(refMethod: any): any;
    static FromReflectedField(refField: any): any;
    static ToReflectedMethod(clazz: any, methodID: any, isStatic: boolean): any;
    static ToReflectedField(clazz: any, fieldID: any, isStatic: boolean): any;
    static GetSuperclass(clazz: any): any;
    static IsAssignableFrom(clazz1: any, clazz2: any): boolean;
    static Throw(obj: any): number;
    static ThrowNew(clazz: any, message: string): number;
    static ExceptionOccurred(): any;
    static ExceptionDescribe(): any;
    static ExceptionClear(): any;
    static FatalError(message: string): any;
    static PushLocalFrame(capacity: number): number;
    static PopLocalFrame(ptr: any): any;
    static NewGlobalRef(obj: any): any;
    static DeleteGlobalRef(obj: any): any;
    static NewLocalRef(obj: any): any;
    static DeleteLocalRef(obj: any): any;
    static IsSameObject(obj1: any, obj2: any): boolean;
    static EnsureLocalCapacity(capacity: number): number;
    static AllocObject(clazz: any): any;
    static NewObject(clazz: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static GetObjectClass(obj: any): any;
    static IsInstanceOf(obj: any, clazz: any): boolean;
    static GetMethodID(clazz: any, name: string, sig: string): any;
    static GetFieldID(clazz: any, name: string, sig: string): any;
    static GetStaticMethodID(clazz: any, name: string, sig: string): any;
    static GetStaticFieldID(clazz: any, name: string, sig: string): any;
    static NewStringUTF(bytes: string): any;
    static GetStringUTFLength(str: any): number;
    static GetStringUTFChars(str: any): string;
    static CallStringMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): string;
    static CallObjectMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static CallIntMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallBooleanMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): boolean;
    static CallShortMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallByteMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallCharMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static CallFloatMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallDoubleMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallLongMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallVoidMethod(obj: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static GetStringField(obj: any, fieldID: any): string;
    static GetObjectField(obj: any, fieldID: any): any;
    static GetBooleanField(obj: any, fieldID: any): boolean;
    static GetByteField(obj: any, fieldID: any): number;
    static GetCharField(obj: any, fieldID: any): any;
    static GetShortField(obj: any, fieldID: any): number;
    static GetIntField(obj: any, fieldID: any): number;
    static GetLongField(obj: any, fieldID: any): number;
    static GetFloatField(obj: any, fieldID: any): number;
    static GetDoubleField(obj: any, fieldID: any): number;
    static SetStringField(obj: any, fieldID: any, val: string): any;
    static SetObjectField(obj: any, fieldID: any, val: any): any;
    static SetBooleanField(obj: any, fieldID: any, val: boolean): any;
    static SetByteField(obj: any, fieldID: any, val: number): any;
    static SetCharField(obj: any, fieldID: any, val: any): any;
    static SetShortField(obj: any, fieldID: any, val: number): any;
    static SetIntField(obj: any, fieldID: any, val: number): any;
    static SetLongField(obj: any, fieldID: any, val: number): any;
    static SetFloatField(obj: any, fieldID: any, val: number): any;
    static SetDoubleField(obj: any, fieldID: any, val: number): any;
    static CallStaticStringMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): string;
    static CallStaticObjectMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static CallStaticIntMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticBooleanMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): boolean;
    static CallStaticShortMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticByteMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticCharMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static CallStaticFloatMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticDoubleMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticLongMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): number;
    static CallStaticVoidMethod(clazz: any, methodID: any, args: UnityEngine.jvalue[]): any;
    static GetStaticStringField(clazz: any, fieldID: any): string;
    static GetStaticObjectField(clazz: any, fieldID: any): any;
    static GetStaticBooleanField(clazz: any, fieldID: any): boolean;
    static GetStaticByteField(clazz: any, fieldID: any): number;
    static GetStaticCharField(clazz: any, fieldID: any): any;
    static GetStaticShortField(clazz: any, fieldID: any): number;
    static GetStaticIntField(clazz: any, fieldID: any): number;
    static GetStaticLongField(clazz: any, fieldID: any): number;
    static GetStaticFloatField(clazz: any, fieldID: any): number;
    static GetStaticDoubleField(clazz: any, fieldID: any): number;
    static SetStaticStringField(clazz: any, fieldID: any, val: string): any;
    static SetStaticObjectField(clazz: any, fieldID: any, val: any): any;
    static SetStaticBooleanField(clazz: any, fieldID: any, val: boolean): any;
    static SetStaticByteField(clazz: any, fieldID: any, val: number): any;
    static SetStaticCharField(clazz: any, fieldID: any, val: any): any;
    static SetStaticShortField(clazz: any, fieldID: any, val: number): any;
    static SetStaticIntField(clazz: any, fieldID: any, val: number): any;
    static SetStaticLongField(clazz: any, fieldID: any, val: number): any;
    static SetStaticFloatField(clazz: any, fieldID: any, val: number): any;
    static SetStaticDoubleField(clazz: any, fieldID: any, val: number): any;
    static ToBooleanArray(array: boolean[]): any;
    static ToByteArray(array: number[]): any;
    static ToCharArray(array: any[]): any;
    static ToShortArray(array: number[]): any;
    static ToIntArray(array: number[]): any;
    static ToLongArray(array: number[]): any;
    static ToFloatArray(array: number[]): any;
    static ToDoubleArray(array: number[]): any;
    static ToObjectArray(array: any[], arrayClass: any): any;
    static ToObjectArray(array: any[]): any;
    static FromBooleanArray(array: any): boolean[];
    static FromByteArray(array: any): number[];
    static FromCharArray(array: any): any[];
    static FromShortArray(array: any): number[];
    static FromIntArray(array: any): number[];
    static FromLongArray(array: any): number[];
    static FromFloatArray(array: any): number[];
    static FromDoubleArray(array: any): number[];
    static FromObjectArray(array: any): any[];
    static GetArrayLength(array: any): number;
    static NewBooleanArray(size: number): any;
    static NewByteArray(size: number): any;
    static NewCharArray(size: number): any;
    static NewShortArray(size: number): any;
    static NewIntArray(size: number): any;
    static NewLongArray(size: number): any;
    static NewFloatArray(size: number): any;
    static NewDoubleArray(size: number): any;
    static NewObjectArray(size: number, clazz: any, obj: any): any;
    static GetBooleanArrayElement(array: any, index: number): boolean;
    static GetByteArrayElement(array: any, index: number): number;
    static GetCharArrayElement(array: any, index: number): any;
    static GetShortArrayElement(array: any, index: number): number;
    static GetIntArrayElement(array: any, index: number): number;
    static GetLongArrayElement(array: any, index: number): number;
    static GetFloatArrayElement(array: any, index: number): number;
    static GetDoubleArrayElement(array: any, index: number): number;
    static GetObjectArrayElement(array: any, index: number): any;
    static SetBooleanArrayElement(array: any, index: number, val: number): any;
    static SetByteArrayElement(array: any, index: number, val: number): any;
    static SetCharArrayElement(array: any, index: number, val: any): any;
    static SetShortArrayElement(array: any, index: number, val: number): any;
    static SetIntArrayElement(array: any, index: number, val: number): any;
    static SetLongArrayElement(array: any, index: number, val: number): any;
    static SetFloatArrayElement(array: any, index: number, val: number): any;
    static SetDoubleArrayElement(array: any, index: number, val: number): any;
    static SetObjectArrayElement(array: any, index: number, obj: any): any;
    // properties
    // fields
  }
}
