declare namespace UnityEngine {
  class Animator {
    // constructors
    constructor();
    // methods
    GetFloat(name: string): number;
    GetFloat(id: number): number;
    SetFloat(name: string, value: number): any;
    SetFloat(name: string, value: number, dampTime: number, deltaTime: number): any;
    SetFloat(id: number, value: number): any;
    SetFloat(id: number, value: number, dampTime: number, deltaTime: number): any;
    GetBool(name: string): boolean;
    GetBool(id: number): boolean;
    SetBool(name: string, value: boolean): any;
    SetBool(id: number, value: boolean): any;
    GetInteger(name: string): number;
    GetInteger(id: number): number;
    SetInteger(name: string, value: number): any;
    SetInteger(id: number, value: number): any;
    SetTrigger(name: string): any;
    SetTrigger(id: number): any;
    ResetTrigger(name: string): any;
    ResetTrigger(id: number): any;
    IsParameterControlledByCurve(name: string): boolean;
    IsParameterControlledByCurve(id: number): boolean;
    GetIKPosition(goal: UnityEngine.AvatarIKGoal): UnityEngine.Vector3;
    SetIKPosition(goal: UnityEngine.AvatarIKGoal, goalPosition: UnityEngine.Vector3): any;
    GetIKRotation(goal: UnityEngine.AvatarIKGoal): UnityEngine.Quaternion;
    SetIKRotation(goal: UnityEngine.AvatarIKGoal, goalRotation: UnityEngine.Quaternion): any;
    GetIKPositionWeight(goal: UnityEngine.AvatarIKGoal): number;
    SetIKPositionWeight(goal: UnityEngine.AvatarIKGoal, value: number): any;
    GetIKRotationWeight(goal: UnityEngine.AvatarIKGoal): number;
    SetIKRotationWeight(goal: UnityEngine.AvatarIKGoal, value: number): any;
    GetIKHintPosition(hint: UnityEngine.AvatarIKHint): UnityEngine.Vector3;
    SetIKHintPosition(hint: UnityEngine.AvatarIKHint, hintPosition: UnityEngine.Vector3): any;
    GetIKHintPositionWeight(hint: UnityEngine.AvatarIKHint): number;
    SetIKHintPositionWeight(hint: UnityEngine.AvatarIKHint, value: number): any;
    SetLookAtPosition(lookAtPosition: UnityEngine.Vector3): any;
    SetLookAtWeight(weight: number, bodyWeight: number, headWeight: number, eyesWeight: number): any;
    SetLookAtWeight(weight: number, bodyWeight: number, headWeight: number): any;
    SetLookAtWeight(weight: number, bodyWeight: number): any;
    SetLookAtWeight(weight: number): any;
    SetLookAtWeight(weight: number, bodyWeight: number, headWeight: number, eyesWeight: number, clampWeight: number): any;
    SetBoneLocalRotation(humanBoneId: UnityEngine.HumanBodyBones, rotation: UnityEngine.Quaternion): any;
    GetLayerName(layerIndex: number): string;
    GetLayerIndex(layerName: string): number;
    GetLayerWeight(layerIndex: number): number;
    SetLayerWeight(layerIndex: number, weight: number): any;
    GetCurrentAnimatorStateInfo(layerIndex: number): UnityEngine.AnimatorStateInfo;
    GetNextAnimatorStateInfo(layerIndex: number): UnityEngine.AnimatorStateInfo;
    GetAnimatorTransitionInfo(layerIndex: number): UnityEngine.AnimatorTransitionInfo;
    GetCurrentAnimatorClipInfoCount(layerIndex: number): number;
    GetCurrentAnimatorClipInfo(layerIndex: number): UnityEngine.AnimatorClipInfo[];
    GetCurrentAnimatorClipInfo(layerIndex: number, clips: any): any;
    GetNextAnimatorClipInfoCount(layerIndex: number): number;
    GetNextAnimatorClipInfo(layerIndex: number): UnityEngine.AnimatorClipInfo[];
    GetNextAnimatorClipInfo(layerIndex: number, clips: any): any;
    IsInTransition(layerIndex: number): boolean;
    GetParameter(index: number): UnityEngine.AnimatorControllerParameter;
    MatchTarget(matchPosition: UnityEngine.Vector3, matchRotation: UnityEngine.Quaternion, targetBodyPart: UnityEngine.AvatarTarget, weightMask: UnityEngine.MatchTargetWeightMask, startNormalizedTime: number, targetNormalizedTime: number): any;
    MatchTarget(matchPosition: UnityEngine.Vector3, matchRotation: UnityEngine.Quaternion, targetBodyPart: UnityEngine.AvatarTarget, weightMask: UnityEngine.MatchTargetWeightMask, startNormalizedTime: number): any;
    InterruptMatchTarget(completeMatch: boolean): any;
    InterruptMatchTarget(): any;
    ForceStateNormalizedTime(normalizedTime: number): any;
    CrossFadeInFixedTime(stateName: string, transitionDuration: number, layer: number): any;
    CrossFadeInFixedTime(stateName: string, transitionDuration: number): any;
    CrossFadeInFixedTime(stateName: string, transitionDuration: number, layer: number, fixedTime: number): any;
    CrossFadeInFixedTime(stateNameHash: number, transitionDuration: number, layer: number, fixedTime: number): any;
    CrossFadeInFixedTime(stateNameHash: number, transitionDuration: number, layer: number): any;
    CrossFadeInFixedTime(stateNameHash: number, transitionDuration: number): any;
    CrossFade(stateName: string, transitionDuration: number, layer: number): any;
    CrossFade(stateName: string, transitionDuration: number): any;
    CrossFade(stateName: string, transitionDuration: number, layer: number, normalizedTime: number): any;
    CrossFade(stateNameHash: number, transitionDuration: number, layer: number, normalizedTime: number): any;
    CrossFade(stateNameHash: number, transitionDuration: number, layer: number): any;
    CrossFade(stateNameHash: number, transitionDuration: number): any;
    PlayInFixedTime(stateName: string, layer: number): any;
    PlayInFixedTime(stateName: string): any;
    PlayInFixedTime(stateName: string, layer: number, fixedTime: number): any;
    PlayInFixedTime(stateNameHash: number, layer: number, fixedTime: number): any;
    PlayInFixedTime(stateNameHash: number, layer: number): any;
    PlayInFixedTime(stateNameHash: number): any;
    Play(stateName: string, layer: number): any;
    Play(stateName: string): any;
    Play(stateName: string, layer: number, normalizedTime: number): any;
    Play(stateNameHash: number, layer: number, normalizedTime: number): any;
    Play(stateNameHash: number, layer: number): any;
    Play(stateNameHash: number): any;
    SetTarget(targetIndex: UnityEngine.AvatarTarget, targetNormalizedTime: number): any;
    IsControlled(transform: UnityEngine.Transform): boolean;
    GetBoneTransform(humanBoneId: UnityEngine.HumanBodyBones): UnityEngine.Transform;
    StartPlayback(): any;
    StopPlayback(): any;
    StartRecording(frameCount: number): any;
    StopRecording(): any;
    HasState(layerIndex: number, stateID: number): boolean;
    static StringToHash(name: string): number;
    Update(deltaTime: number): any;
    Rebind(): any;
    ApplyBuiltinRootMotion(): any;
    GetVector(name: string): UnityEngine.Vector3;
    GetVector(id: number): UnityEngine.Vector3;
    SetVector(name: string, value: UnityEngine.Vector3): any;
    SetVector(id: number, value: UnityEngine.Vector3): any;
    GetQuaternion(name: string): UnityEngine.Quaternion;
    GetQuaternion(id: number): UnityEngine.Quaternion;
    SetQuaternion(name: string, value: UnityEngine.Quaternion): any;
    SetQuaternion(id: number, value: UnityEngine.Quaternion): any;
    GetCurrentAnimationClipState(layerIndex: number): UnityEngine.AnimationInfo[];
    GetNextAnimationClipState(layerIndex: number): UnityEngine.AnimationInfo[];
    Play(pStruct: UnityEngine.Experimental.Director.Playable): any;
    Stop(): any;
    SetTime(time: number): any;
    GetTime(): number;
    SetTimeUpdateMode(mode: UnityEngine.Experimental.Director.DirectorUpdateMode): any;
    GetTimeUpdateMode(): UnityEngine.Experimental.Director.DirectorUpdateMode;
    GetComponent(type: any): UnityEngine.Component;
    GetComponent(type: string): UnityEngine.Component;
    GetComponentInChildren(t: any, includeInactive: boolean): UnityEngine.Component;
    GetComponentInChildren(t: any): UnityEngine.Component;
    GetComponentsInChildren(t: any): UnityEngine.Component[];
    GetComponentsInChildren(t: any, includeInactive: boolean): UnityEngine.Component[];
    GetComponentInParent(t: any): UnityEngine.Component;
    GetComponentsInParent(t: any): UnityEngine.Component[];
    GetComponentsInParent(t: any, includeInactive: boolean): UnityEngine.Component[];
    GetComponents(type: any): UnityEngine.Component[];
    GetComponents(type: any, results: any): any;
    CompareTag(tag: string): boolean;
    SendMessageUpwards(methodName: string, value: any, options: UnityEngine.SendMessageOptions): any;
    SendMessageUpwards(methodName: string, value: any): any;
    SendMessageUpwards(methodName: string): any;
    SendMessageUpwards(methodName: string, options: UnityEngine.SendMessageOptions): any;
    SendMessage(methodName: string, value: any, options: UnityEngine.SendMessageOptions): any;
    SendMessage(methodName: string, value: any): any;
    SendMessage(methodName: string): any;
    SendMessage(methodName: string, options: UnityEngine.SendMessageOptions): any;
    BroadcastMessage(methodName: string, parameter: any, options: UnityEngine.SendMessageOptions): any;
    BroadcastMessage(methodName: string, parameter: any): any;
    BroadcastMessage(methodName: string): any;
    BroadcastMessage(methodName: string, options: UnityEngine.SendMessageOptions): any;
    ToString(): string;
    GetInstanceID(): number;
    GetHashCode(): number;
    Equals(other: any): boolean;
    GetType(): any;
    // properties
    readonly isOptimizable: boolean;
    readonly isHuman: boolean;
    readonly hasRootMotion: boolean;
    readonly humanScale: number;
    readonly isInitialized: boolean;
    readonly deltaPosition: UnityEngine.Vector3;
    readonly deltaRotation: UnityEngine.Quaternion;
    readonly velocity: UnityEngine.Vector3;
    readonly angularVelocity: UnityEngine.Vector3;
    rootPosition: UnityEngine.Vector3;
    rootRotation: UnityEngine.Quaternion;
    applyRootMotion: boolean;
    linearVelocityBlending: boolean;
    animatePhysics: boolean;
    updateMode: UnityEngine.AnimatorUpdateMode;
    readonly hasTransformHierarchy: boolean;
    readonly gravityWeight: number;
    bodyPosition: UnityEngine.Vector3;
    bodyRotation: UnityEngine.Quaternion;
    stabilizeFeet: boolean;
    readonly layerCount: number;
    readonly parameters: UnityEngine.AnimatorControllerParameter[];
    readonly parameterCount: number;
    feetPivotActive: number;
    readonly pivotWeight: number;
    readonly pivotPosition: UnityEngine.Vector3;
    readonly isMatchingTarget: boolean;
    speed: number;
    readonly targetPosition: UnityEngine.Vector3;
    readonly targetRotation: UnityEngine.Quaternion;
    cullingMode: UnityEngine.AnimatorCullingMode;
    playbackTime: number;
    recorderStartTime: number;
    recorderStopTime: number;
    readonly recorderMode: UnityEngine.AnimatorRecorderMode;
    runtimeAnimatorController: UnityEngine.RuntimeAnimatorController;
    avatar: UnityEngine.Avatar;
    layersAffectMassCenter: boolean;
    readonly leftFeetBottomHeight: number;
    readonly rightFeetBottomHeight: number;
    logWarnings: boolean;
    fireEvents: boolean;
    enabled: boolean;
    readonly isActiveAndEnabled: boolean;
    readonly transform: UnityEngine.Transform;
    readonly gameObject: UnityEngine.GameObject;
    tag: string;
    readonly rigidbody: UnityEngine.Component;
    readonly rigidbody2D: UnityEngine.Component;
    readonly camera: UnityEngine.Component;
    readonly light: UnityEngine.Component;
    readonly animation: UnityEngine.Component;
    readonly constantForce: UnityEngine.Component;
    readonly renderer: UnityEngine.Component;
    readonly audio: UnityEngine.Component;
    readonly guiText: UnityEngine.Component;
    readonly networkView: UnityEngine.Component;
    readonly guiElement: UnityEngine.Component;
    readonly guiTexture: UnityEngine.Component;
    readonly collider: UnityEngine.Component;
    readonly collider2D: UnityEngine.Component;
    readonly hingeJoint: UnityEngine.Component;
    readonly particleEmitter: UnityEngine.Component;
    readonly particleSystem: UnityEngine.Component;
    name: string;
    hideFlags: UnityEngine.HideFlags;
    // fields
  }
}
