declare namespace UnityEngine {
  class Rigidbody2D {
    // constructors
    constructor();
    // methods
    MovePosition(position: UnityEngine.Vector2): void;
    MoveRotation(angle: number): void;
    IsSleeping(): boolean;
    IsAwake(): boolean;
    Sleep(): void;
    WakeUp(): void;
    IsTouching(collider: UnityEngine.Collider2D): boolean;
    IsTouchingLayers(layerMask: number): boolean;
    IsTouchingLayers(): boolean;
    OverlapPoint(point: UnityEngine.Vector2): boolean;
    Cast(direction: UnityEngine.Vector2, results: UnityEngine.RaycastHit2D[], distance: number): number;
    Cast(direction: UnityEngine.Vector2, results: UnityEngine.RaycastHit2D[]): number;
    AddForce(force: UnityEngine.Vector2, mode: UnityEngine.ForceMode2D): void;
    AddForce(force: UnityEngine.Vector2): void;
    AddRelativeForce(relativeForce: UnityEngine.Vector2, mode: UnityEngine.ForceMode2D): void;
    AddRelativeForce(relativeForce: UnityEngine.Vector2): void;
    AddForceAtPosition(force: UnityEngine.Vector2, position: UnityEngine.Vector2, mode: UnityEngine.ForceMode2D): void;
    AddForceAtPosition(force: UnityEngine.Vector2, position: UnityEngine.Vector2): void;
    AddTorque(torque: number, mode: UnityEngine.ForceMode2D): void;
    AddTorque(torque: number): void;
    GetPoint(point: UnityEngine.Vector2): UnityEngine.Vector2;
    GetRelativePoint(relativePoint: UnityEngine.Vector2): UnityEngine.Vector2;
    GetVector(vector: UnityEngine.Vector2): UnityEngine.Vector2;
    GetRelativeVector(relativeVector: UnityEngine.Vector2): UnityEngine.Vector2;
    GetPointVelocity(point: UnityEngine.Vector2): UnityEngine.Vector2;
    GetRelativePointVelocity(relativePoint: UnityEngine.Vector2): UnityEngine.Vector2;
    GetComponent(type: any): UnityEngine.Component;
    GetComponent(type: string): UnityEngine.Component;
    GetComponentInChildren(t: any, includeInactive: boolean): UnityEngine.Component;
    GetComponentInChildren(t: any): UnityEngine.Component;
    GetComponentsInChildren(t: any): UnityEngine.Component[];
    GetComponentsInChildren(t: any, includeInactive: boolean): UnityEngine.Component[];
    GetComponentInParent(t: any): UnityEngine.Component;
    GetComponentsInParent(t: any): UnityEngine.Component[];
    GetComponentsInParent(t: any, includeInactive: boolean): UnityEngine.Component[];
    GetComponents(type: any): UnityEngine.Component[];
    GetComponents(type: any, results: any): void;
    CompareTag(tag: string): boolean;
    SendMessageUpwards(methodName: string, value: any, options: UnityEngine.SendMessageOptions): void;
    SendMessageUpwards(methodName: string, value: any): void;
    SendMessageUpwards(methodName: string): void;
    SendMessageUpwards(methodName: string, options: UnityEngine.SendMessageOptions): void;
    SendMessage(methodName: string, value: any, options: UnityEngine.SendMessageOptions): void;
    SendMessage(methodName: string, value: any): void;
    SendMessage(methodName: string): void;
    SendMessage(methodName: string, options: UnityEngine.SendMessageOptions): void;
    BroadcastMessage(methodName: string, parameter: any, options: UnityEngine.SendMessageOptions): void;
    BroadcastMessage(methodName: string, parameter: any): void;
    BroadcastMessage(methodName: string): void;
    BroadcastMessage(methodName: string, options: UnityEngine.SendMessageOptions): void;
    ToString(): string;
    GetInstanceID(): number;
    GetHashCode(): number;
    Equals(other: any): boolean;
    GetType(): any;
    // properties
    position: UnityEngine.Vector2;
    rotation: number;
    velocity: UnityEngine.Vector2;
    angularVelocity: number;
    useAutoMass: boolean;
    mass: number;
    sharedMaterial: UnityEngine.PhysicsMaterial2D;
    centerOfMass: UnityEngine.Vector2;
    readonly worldCenterOfMass: UnityEngine.Vector2;
    inertia: number;
    drag: number;
    angularDrag: number;
    gravityScale: number;
    bodyType: UnityEngine.RigidbodyType2D;
    useFullKinematicContacts: boolean;
    isKinematic: boolean;
    fixedAngle: boolean;
    freezeRotation: boolean;
    constraints: UnityEngine.RigidbodyConstraints2D;
    simulated: boolean;
    interpolation: UnityEngine.RigidbodyInterpolation2D;
    sleepMode: UnityEngine.RigidbodySleepMode2D;
    collisionDetectionMode: UnityEngine.CollisionDetectionMode2D;
    readonly transform: UnityEngine.Transform;
    readonly gameObject: UnityEngine.GameObject;
    tag: string;
    readonly rigidbody: UnityEngine.Component;
    readonly rigidbody2D: UnityEngine.Component;
    readonly camera: UnityEngine.Component;
    readonly light: UnityEngine.Component;
    readonly animation: UnityEngine.Component;
    readonly constantForce: UnityEngine.Component;
    readonly renderer: UnityEngine.Component;
    readonly audio: UnityEngine.Component;
    readonly guiText: UnityEngine.Component;
    readonly networkView: UnityEngine.Component;
    readonly guiElement: UnityEngine.Component;
    readonly guiTexture: UnityEngine.Component;
    readonly collider: UnityEngine.Component;
    readonly collider2D: UnityEngine.Component;
    readonly hingeJoint: UnityEngine.Component;
    readonly particleEmitter: UnityEngine.Component;
    readonly particleSystem: UnityEngine.Component;
    name: string;
    hideFlags: UnityEngine.HideFlags;
    // fields
  }
}
