declare namespace UnityEngine {
  class GUILayout {
    // constructors
    constructor();
    // methods
    static Label(image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): any;
    static Label(text: string, options: UnityEngine.GUILayoutOption[]): any;
    static Label(content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): any;
    static Label(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Label(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Label(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Box(image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): any;
    static Box(text: string, options: UnityEngine.GUILayoutOption[]): any;
    static Box(content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): any;
    static Box(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Box(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Box(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static Button(image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): boolean;
    static Button(text: string, options: UnityEngine.GUILayoutOption[]): boolean;
    static Button(content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): boolean;
    static Button(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static Button(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static Button(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(text: string, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static RepeatButton(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static TextField(text: string, options: UnityEngine.GUILayoutOption[]): string;
    static TextField(text: string, maxLength: number, options: UnityEngine.GUILayoutOption[]): string;
    static TextField(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static TextField(text: string, maxLength: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static PasswordField(password: string, maskChar: any, options: UnityEngine.GUILayoutOption[]): string;
    static PasswordField(password: string, maskChar: any, maxLength: number, options: UnityEngine.GUILayoutOption[]): string;
    static PasswordField(password: string, maskChar: any, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static PasswordField(password: string, maskChar: any, maxLength: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static TextArea(text: string, options: UnityEngine.GUILayoutOption[]): string;
    static TextArea(text: string, maxLength: number, options: UnityEngine.GUILayoutOption[]): string;
    static TextArea(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static TextArea(text: string, maxLength: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): string;
    static Toggle(value: boolean, image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toggle(value: boolean, text: string, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toggle(value: boolean, content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toggle(value: boolean, image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toggle(value: boolean, text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toggle(value: boolean, content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): boolean;
    static Toolbar(selected: number, texts: string[], options: UnityEngine.GUILayoutOption[]): number;
    static Toolbar(selected: number, images: UnityEngine.Texture[], options: UnityEngine.GUILayoutOption[]): number;
    static Toolbar(selected: number, content: UnityEngine.GUIContent[], options: UnityEngine.GUILayoutOption[]): number;
    static Toolbar(selected: number, texts: string[], style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static Toolbar(selected: number, images: UnityEngine.Texture[], style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static Toolbar(selected: number, contents: UnityEngine.GUIContent[], style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, texts: string[], xCount: number, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, images: UnityEngine.Texture[], xCount: number, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, content: UnityEngine.GUIContent[], xCount: number, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, texts: string[], xCount: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, images: UnityEngine.Texture[], xCount: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static SelectionGrid(selected: number, contents: UnityEngine.GUIContent[], xCount: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static HorizontalSlider(value: number, leftValue: number, rightValue: number, options: UnityEngine.GUILayoutOption[]): number;
    static HorizontalSlider(value: number, leftValue: number, rightValue: number, slider: UnityEngine.GUIStyle, thumb: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static VerticalSlider(value: number, leftValue: number, rightValue: number, options: UnityEngine.GUILayoutOption[]): number;
    static VerticalSlider(value: number, leftValue: number, rightValue: number, slider: UnityEngine.GUIStyle, thumb: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static HorizontalScrollbar(value: number, size: number, leftValue: number, rightValue: number, options: UnityEngine.GUILayoutOption[]): number;
    static HorizontalScrollbar(value: number, size: number, leftValue: number, rightValue: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static VerticalScrollbar(value: number, size: number, topValue: number, bottomValue: number, options: UnityEngine.GUILayoutOption[]): number;
    static VerticalScrollbar(value: number, size: number, topValue: number, bottomValue: number, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): number;
    static Space(pixels: number): any;
    static FlexibleSpace(): any;
    static BeginHorizontal(options: UnityEngine.GUILayoutOption[]): any;
    static BeginHorizontal(style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginHorizontal(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginHorizontal(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginHorizontal(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static EndHorizontal(): any;
    static BeginVertical(options: UnityEngine.GUILayoutOption[]): any;
    static BeginVertical(style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginVertical(text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginVertical(image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static BeginVertical(content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): any;
    static EndVertical(): any;
    static BeginArea(screenRect: UnityEngine.Rect): any;
    static BeginArea(screenRect: UnityEngine.Rect, text: string): any;
    static BeginArea(screenRect: UnityEngine.Rect, image: UnityEngine.Texture): any;
    static BeginArea(screenRect: UnityEngine.Rect, content: UnityEngine.GUIContent): any;
    static BeginArea(screenRect: UnityEngine.Rect, style: UnityEngine.GUIStyle): any;
    static BeginArea(screenRect: UnityEngine.Rect, text: string, style: UnityEngine.GUIStyle): any;
    static BeginArea(screenRect: UnityEngine.Rect, image: UnityEngine.Texture, style: UnityEngine.GUIStyle): any;
    static BeginArea(screenRect: UnityEngine.Rect, content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle): any;
    static EndArea(): any;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, alwaysShowHorizontal: boolean, alwaysShowVertical: boolean, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, horizontalScrollbar: UnityEngine.GUIStyle, verticalScrollbar: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, style: UnityEngine.GUIStyle): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, alwaysShowHorizontal: boolean, alwaysShowVertical: boolean, horizontalScrollbar: UnityEngine.GUIStyle, verticalScrollbar: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static BeginScrollView(scrollPosition: UnityEngine.Vector2, alwaysShowHorizontal: boolean, alwaysShowVertical: boolean, horizontalScrollbar: UnityEngine.GUIStyle, verticalScrollbar: UnityEngine.GUIStyle, background: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Vector2;
    static EndScrollView(): any;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, text: string, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, image: UnityEngine.Texture, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, content: UnityEngine.GUIContent, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, text: string, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, image: UnityEngine.Texture, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Window(id: number, screenRect: UnityEngine.Rect, func: UnityEngine.GUI.WindowFunction, content: UnityEngine.GUIContent, style: UnityEngine.GUIStyle, options: UnityEngine.GUILayoutOption[]): UnityEngine.Rect;
    static Width(width: number): UnityEngine.GUILayoutOption;
    static MinWidth(minWidth: number): UnityEngine.GUILayoutOption;
    static MaxWidth(maxWidth: number): UnityEngine.GUILayoutOption;
    static Height(height: number): UnityEngine.GUILayoutOption;
    static MinHeight(minHeight: number): UnityEngine.GUILayoutOption;
    static MaxHeight(maxHeight: number): UnityEngine.GUILayoutOption;
    static ExpandWidth(expand: boolean): UnityEngine.GUILayoutOption;
    static ExpandHeight(expand: boolean): UnityEngine.GUILayoutOption;
    Equals(obj: any): boolean;
    GetHashCode(): number;
    GetType(): any;
    ToString(): string;
    // properties
    // fields
  }
}
